config:
  access_token: AcCeSsToKeN # GitHub Personal access token
  sleep_time: 900 # How often to run the checks, in seconds - defaults to 1800 (30 mins)

# The name of a GH repo you have push access to
spritsail/nzbhydra:
  branch: master
  args:
    NZBHYDRA_VER:
      url: https://api.github.com/repos/theotherp/nzbhydra2/releases
      structure: 0.tag_name
      human_name: NZBHydra
      strip_front: v
    YQ_VER:
      url: https://api.github.com/repos/mikefarah/yq/releases
      structure: 0.tag_name
      human_name: YQ
